services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: scrappymarket_db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "IT7993!Scrappy"
    ports:
      - "1433:1433"
    volumes:
      - ../db:/db
      - ./init-db.sh:/init-db.sh
    command: /bin/bash -c "/init-db.sh & /opt/mssql/bin/sqlservr"
